language: java
sudo: false
  #script: mvn clean verify
addons:
  sonarcloud:
    organization: "lucamastro"
    token:
      secure: "QkWjKg3XWD1o9PwllCIUf51MEgJ0qpV1Ppd5gxetPyzSYCKIKHfKBfytqBcDZCCng6g26iV+eV9qUV8ByquPC5q1WyAF1DaCuHEvjz9ErFlX7NrR75UDaN+I9qmD6FqBRtZj9eE1J8WYYbtJQKjpGh+PzLqeap8uOYBjN5z2u/7GfaX2WnXc7DDkY7bdXCcRBxiaPpsEp7v2VnqgnZapItnLEwlGpx/pxPT76IfwyrQ2Y5X8gE93OTlVw9AYoSl59eDily0mHXUkAVgb+DTwtDfrkHSVOvAmGVyIsIyGlD4POEIYctykkJOIoRRw67jZVpouL14k7qBzE7xadhum5xEEmd3lxsScGZcRJ6PrVIC9l2SzdoEuFvC8AY3koO/IcP6PGw+ZKxf9eI5WNGUHHnoxZd42fy7WfY0wXz+3rtO8nlIt6xOrCNoBrWDF9OUl/sQ95Bjp9AWcU0BQb4fAz6JNeCQ25ORDLB8rkMIryMiUI5JvKtDhIewTat77QPsvp3gChfsBxyScYOXMBe+E+cQ9aTvdGzBPdQOQrfTN1gcClBPXUn9KOuP5hJmYslQ+57H/wPg6QetquMODDnw1WDT8MAb43Owb/0lGMTUmBeS5aiiTal6eh4kEGAL25u+LQmRk/lvLIVxDFFG2voEFM+yqv7KsRkF9Pz6Oct+mzkw="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
