language: java
sudo: false
addons:
  sonarcloud:
    organization: "lucamastro"
    token:
      secure: "FkYid3A65tinoLkKPCMcbeahuR72G8rCvrQF6VobF2S8qurZ5QEGlVE0iSm/kecfP3KJPnTW7e0qi4zPC/JDIxua5i+GyUaTr98OX9EPKDO+OxStEuNJTrggrjJ29wfQPWshpUhEJ7wLxzO4fKJ/wHm76dpjVzfJSSonefHkCobc3u8gamg+0U1waAEtktO+mA96o82J6jYKnPkBrFQYUtLBN3scgP6pOUJ8yQegj2VmyW1Qijbj5Afp7UoSZCr38mGaQolAgjvKj11WzHrMElnw1liGt2oUSW1wPnBLyqs210on5HUlWxQWhFs3YqalakYXPhNpcHSzuzZSSUVHn0sIDOKzYQYQ3KFsPtkofpINDfkakhFQoYzdtxu0jIikzEoSJtzFEJdrTqYMg8DxBvOPDfhbTEOnjPO4fW+UTCiCWHrqSuynYLJCIq6Hz/3rTfH8yGjXicpY1SoKB6c172qMvf5P0vuSYLk+RIpMl/Tx4XOAsFP/J/2u6qUPLnPIxc8wIec0iRLKA08YNQXC4+CxPrseZdjeucws3upl4AZGlSD51amrsapUpUN7OO0BZdYK2Z1vs3jtaoVLnhC+HGLAfeuRvBx8t9yMkGHM9mFJoRKBc1Z3hisCv1OgQdxEBYHYPgiQM5QBHmiZgsFVQ7xeYX/Nf15Z0XwdtuVzYNQ=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
