language: java
sudo: false
  #script: mvn clean verify
addons:
  sonarcloud:
    organization: "lucamastro"
    token:
      secure: "QHRD/zL8yDyuOTH1rx4LC/xccN2fo3CwDPmQxkc3i+hx0atY+kvIveHBDxj2wByCHrAR1pFwu1YcRPhZ+xnFnL4aqb3tDFVklEE3JInhHhp8rptC/4qxz+NCJ7IB0Zl/bQuPkHH3XkwTL5l5E2h7G5w2rpoNCcWFsUXX2C69xAIzJE5EOmMG1R9lme9DY2PGiWQkXNcXVYDZ3SFx4VHwMqoDOWzJLSYXqOZPLB0IoxfrebRmrYpxd0rV/WZ1s8GvJ5Xi64X8ngPBW6bLWxqAWtS5k29CD0OJdwRYNRjds7gzHByOWG9hJep1KImRsBLbQ6wexif0pRfCPymEyOZYN7O1vHqYjxGhSjh+BukwLiIGZkn2OCS+InhF2G/IzvG1oAYSiy9bVLRJC0aXsBjMnd2CsNvE7gV+Poh3HvbYxZ5zM/g1h1X1kYefjcnmgKihFdcGW3hrN6r9JSdOnqQv1Q4FYfQl/BQY+e83BtyIBXOvu9Bj+0J0QppwkMoZIrc7QmK4TSp29+wbfMimwn7KkBBtSaDQqsrd2eXFR/pZnYkpBGNjiKEju4HAKhPgTGW/osMcZHZsAVGOaJtNNznOi/CKbDFDKageXJq/IM/NdKeCyP+Hmc7GidCA521AHO+9LubRB3uigLDSqdtnfAK2jwTb57feD6S1f/Q8msIebyY="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
